services:
  mongodb:
    image: mongo:7
    container_name: mylist-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mylist

volumes:
  mongodb_data:
